// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kubenet} from '../models';
import {sync} from '../models';

export function AddStatusListener(arg1:any):Promise<void>;

export function GetNodeByID(arg1:string):Promise<kubenet.Node|boolean>;

export function GetNodes():Promise<Array<kubenet.Node>>;

export function GetNodesForFrontend():Promise<Array<Record<string, any>>>;

export function GetNodesForFrontend_old():Promise<Array<Record<string, any>>>;

export function Lock():Promise<void>;

export function LockNode():Promise<void>;

export function RLock():Promise<void>;

export function RLocker():Promise<sync.Locker>;

export function RUnlock():Promise<void>;

export function SetNodeStatus(arg1:string):Promise<void>;

export function Start(arg1:any):Promise<void>;

export function TryLock():Promise<boolean>;

export function TryRLock():Promise<boolean>;

export function Unlock():Promise<void>;

export function UnlockNode():Promise<void>;
