// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStatusListener(arg1) {
  return window['go']['kubenet']['NodeRegistry']['AddStatusListener'](arg1);
}

export function GetNodeByID(arg1) {
  return window['go']['kubenet']['NodeRegistry']['GetNodeByID'](arg1);
}

export function GetNodes() {
  return window['go']['kubenet']['NodeRegistry']['GetNodes']();
}

export function GetNodesForFrontend() {
  return window['go']['kubenet']['NodeRegistry']['GetNodesForFrontend']();
}

export function GetNodesForFrontend_old() {
  return window['go']['kubenet']['NodeRegistry']['GetNodesForFrontend_old']();
}

export function Lock() {
  return window['go']['kubenet']['NodeRegistry']['Lock']();
}

export function LockNode() {
  return window['go']['kubenet']['NodeRegistry']['LockNode']();
}

export function RLock() {
  return window['go']['kubenet']['NodeRegistry']['RLock']();
}

export function RLocker() {
  return window['go']['kubenet']['NodeRegistry']['RLocker']();
}

export function RUnlock() {
  return window['go']['kubenet']['NodeRegistry']['RUnlock']();
}

export function SetNodeStatus(arg1) {
  return window['go']['kubenet']['NodeRegistry']['SetNodeStatus'](arg1);
}

export function Start(arg1) {
  return window['go']['kubenet']['NodeRegistry']['Start'](arg1);
}

export function TryLock() {
  return window['go']['kubenet']['NodeRegistry']['TryLock']();
}

export function TryRLock() {
  return window['go']['kubenet']['NodeRegistry']['TryRLock']();
}

export function Unlock() {
  return window['go']['kubenet']['NodeRegistry']['Unlock']();
}

export function UnlockNode() {
  return window['go']['kubenet']['NodeRegistry']['UnlockNode']();
}
