// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyItem(arg1, arg2) {
  return window['go']['kfiles']['FileBrowser']['CopyItem'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['kfiles']['FileBrowser']['CreateFolder'](arg1, arg2);
}

export function DeleteItem(arg1) {
  return window['go']['kfiles']['FileBrowser']['DeleteItem'](arg1);
}

export function DownloadFile(arg1) {
  return window['go']['kfiles']['FileBrowser']['DownloadFile'](arg1);
}

export function GetCurrentPath(arg1) {
  return window['go']['kfiles']['FileBrowser']['GetCurrentPath'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['kfiles']['FileBrowser']['GetFileInfo'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['kfiles']['FileBrowser']['ListDirectory'](arg1);
}

export function MoveItem(arg1, arg2) {
  return window['go']['kfiles']['FileBrowser']['MoveItem'](arg1, arg2);
}

export function RefrigerateFile(arg1) {
  return window['go']['kfiles']['FileBrowser']['RefrigerateFile'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['kfiles']['FileBrowser']['RenameItem'](arg1, arg2);
}

export function UnrefrigerateFile(arg1) {
  return window['go']['kfiles']['FileBrowser']['UnrefrigerateFile'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['kfiles']['FileBrowser']['UploadFile'](arg1, arg2, arg3);
}
