// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetCurrentUser():Promise<string>;

export function IsInitialized():Promise<boolean>;

export function LoginUserWithFrame(arg1:string,arg2:string):Promise<string>;

export function Logout():Promise<void>;

export function TrainNewUserWithFrames(arg1:string,arg2:Array<string>):Promise<string>;
