// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function GetCurrentUser():Promise<string>;

export function GetRegisteredUserCount():Promise<number>;

export function IsInitialized():Promise<boolean>;

export function LoginUser():Promise<string>;

export function Logout():Promise<void>;

export function TrainNewUser(arg1:string):Promise<string>;
