// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['security']['FacialSystem']['Close']();
}

export function GetCurrentUser() {
  return window['go']['security']['FacialSystem']['GetCurrentUser']();
}

export function GetRegisteredUserCount() {
  return window['go']['security']['FacialSystem']['GetRegisteredUserCount']();
}

export function IsInitialized() {
  return window['go']['security']['FacialSystem']['IsInitialized']();
}

export function LoginUser() {
  return window['go']['security']['FacialSystem']['LoginUser']();
}

export function Logout() {
  return window['go']['security']['FacialSystem']['Logout']();
}

export function TrainNewUser(arg1) {
  return window['go']['security']['FacialSystem']['TrainNewUser'](arg1);
}
