// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['security']['FacialSystem']['Close']();
}

export function GetCurrentUser() {
  return window['go']['security']['FacialSystem']['GetCurrentUser']();
}

export function IsInitialized() {
  return window['go']['security']['FacialSystem']['IsInitialized']();
}

export function LoginUserWithFrame(arg1, arg2) {
  return window['go']['security']['FacialSystem']['LoginUserWithFrame'](arg1, arg2);
}

export function Logout() {
  return window['go']['security']['FacialSystem']['Logout']();
}

export function TrainNewUserWithFrames(arg1, arg2) {
  return window['go']['security']['FacialSystem']['TrainNewUserWithFrames'](arg1, arg2);
}
