// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {security} from '../models';

export function CleanupExpiredSessions():Promise<void>;

export function GetCurrentUser(arg1:string):Promise<security.User>;

export function IsUserAdmin(arg1:number):Promise<boolean>;

export function LoginWithCredentials(arg1:string,arg2:string):Promise<security.AuthResponse>;

export function LoginWithFacialAuth(arg1:string):Promise<security.AuthResponse>;

export function Logout(arg1:string):Promise<void>;

export function RegisterUser(arg1:security.RegistrationRequest):Promise<security.AuthResponse>;

export function ValidateSession(arg1:string):Promise<security.User>;
