// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupExpiredSessions() {
  return window['go']['security']['UserManager']['CleanupExpiredSessions']();
}

export function GetCurrentUser(arg1) {
  return window['go']['security']['UserManager']['GetCurrentUser'](arg1);
}

export function IsUserAdmin(arg1) {
  return window['go']['security']['UserManager']['IsUserAdmin'](arg1);
}

export function LoginWithCredentials(arg1, arg2) {
  return window['go']['security']['UserManager']['LoginWithCredentials'](arg1, arg2);
}

export function LoginWithFacialAuth() {
  return window['go']['security']['UserManager']['LoginWithFacialAuth']();
}

export function Logout(arg1) {
  return window['go']['security']['UserManager']['Logout'](arg1);
}

export function RegisterUser(arg1) {
  return window['go']['security']['UserManager']['RegisterUser'](arg1);
}

export function ValidateSession(arg1) {
  return window['go']['security']['UserManager']['ValidateSession'](arg1);
}
