// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileBrowser() {
  return window['go']['main']['App']['GetFileBrowser']();
}

export function GetNodeRegistry() {
  return window['go']['main']['App']['GetNodeRegistry']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
