// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kfiles} from '../models';
import {kubenet} from '../models';

export function GetFileBrowser():Promise<kfiles.FileBrowser>;

export function GetNodeRegistry():Promise<kubenet.NodeRegistry>;

export function Greet(arg1:string):Promise<string>;
